development:
  access_key_id: AKIAJXWG2UO2FVTJVG3Q
  secret_access_key: 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

production:
  access_key_id: AKIAJXWG2UO2FVTJVG3Q
  secret_access_key: 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
